import os

Import('env')

lib_name = 'boost_python_exception'

lib = env.SharedLibrary(
    lib_name,
    source=['get_exception_info.cpp'])

test_env = env.Clone()
test_env.AppendUnique(CPPDEFINES=['BOOST_TEST_DYN_LINK'])
test_env.Append(LIBS=[lib_name])
test_env.Append(LIBPATH=[os.path.abspath('.')])

test_bin = test_env.Program(
    'boost_python_exception_test',
    source=['tests.cpp'])
