Import(['env'])

env = env.Clone()
env.AppendUnique(CPPDEFINES=['BOOST_TEST_DYN_LINK'])

################################################################################
# Build everything

env.Append(CXXFLAGS=['-g', '-O0'])

test_bin = env.Program(
    'boost_python_exception_test',
    source=['tests.cpp',
            env['bpex_library']])

env.Install(
    '$INSTALL_DIR',
    test_bin)
