def configure(conf):
    conf.load('boost')
    
    conf.check_boost(lib='unit_test',
                     mt=False,
                     stlib=False,
                     uselib_store='BOOST_UNIT_TEST')

def build(bld):
    bld.program(source=bld.path.ant_glob('**/*.cpp'),
                target='boost_python_exception_tests',
                defines=['BOOST_TEST_DYN_LINK'],
                use='boost_python_exception BOOST_UNIT_TEST',
                features='pyembed')
