language: cpp
compiler:
    - gcc
    - clang
    
before_install:
    - sudo apt-get -y install python-dev libboost-dev libboost-python-dev libboost-test-dev libboost-system-dev
    
script:
    - python waf update --files=boost
    - python waf configure
    - cat /home/travis/build/abingham/boost_python_exception/build_directory/config.log
    - python waf build -v
    - LD_LIBRARY_PATH=build_directory/src/boost_python_exception/ ./build_directory/src/test/boost_python_exception_tests

